#choose if you want prefix/suffix to have additions.
include-prefix-additions: true
include-suffix-additions: true
#This is the layout of your formatted prefix, and suffix
prefix-layout: '&7[{META}&7]'
suffix-layout: '&7[{META}&7]'
#how many meta tokens should each player start with?
#starting-amount: 0