name: MetaTokens
main: dev.Ev1dent.MetaTokens.MTMain
version: ${project.version}
authors: [Ev1dent, Evident#0812 (discord)]
website: git.ev1dent.me
commands:
  setprefix:
    description: set your prefix
    usage: "/setprefix <prefix>"
  setsuffix:
    description: set your suffix
    usage: "/setsuffix <suffix>"
  tokens:
    description: command to see token amount.
  metatokens:
    description: main plugin command
permissions:
  metatokens.commands:
    children:
      - metatokens.setprefix
      - metatokens.setsuffix
    default: true
